export default [
  {
    name: "Leonardo Matallana",
    nick: "Leo",
    avatar: "https://ca.slack-edge.com/T0351LEFK-UP60MA0BF-839017f936e9-512",
    project:
      "https://cbx-80a0.kxcdn.com/wp-content/uploads/2019/12/eci-logo-1024x267.png",
    rating: 3.5,
    position: "FE",
    features: [
      { value: "4.0", title: "FE" },
      { value: "2.83", title: "BE" },
      { value: "0.75", title: "DO" },
      { value: "3.66", title: "MM" },
      { value: "4.5", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Juan Perez",
    nick: "Juan simon",
    avatar: "https://ca.slack-edge.com/T0351LEFK-UQU2FFLMS-e4682d2bc852-512",
    project:
      "https://cbx-80a0.kxcdn.com/wp-content/uploads/2019/12/eci-logo-1024x267.png",
    rating: 4.7,
    position: "FE",
    features: [
      { value: "4.2", title: "FE" },
      { value: "4.6", title: "BE" },
      { value: "3.5", title: "DO" },
      { value: "5.5", title: "MM" },
      { value: "5.3", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Jose Ramirez",
    nick: "Jose",
    avatar: "https://ca.slack-edge.com/T0351LEFK-U014QAGN4AY-aee2526839e1-512",
    project:
      "https://cbx-80a0.kxcdn.com/wp-content/uploads/2019/12/eci-logo-1024x267.png",
    rating: 5.1,
    position: "BE",
    features: [
      { value: "4.3", title: "FE" },
      { value: "4.2", title: "BE" },
      { value: "5.2", title: "DO" },
      { value: "7.1", title: "MM" },
      { value: "5.5", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Miguel Cardenas",
    nick: "Migue",
    avatar: "https://ca.slack-edge.com/T0351LEFK-U6LTQSD5X-86af3a91d92e-512",
    project:
      "https://cbx-80a0.kxcdn.com/wp-content/uploads/2019/12/eci-logo-1024x267.png",
    rating: 5.1,
    position: "FE",
    features: [
      { value: "5", title: "FE" },
      { value: "4", title: "BE" },
      { value: "2.7", title: "DO" },
      { value: "6.5", title: "MM" },
      { value: "6.5", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Sergio Florez",
    nick: "Sergio",
    avatar: "https://ca.slack-edge.com/T0351LEFK-U58AY0MRD-208a0ae1e8be-512",
    project:
      "https://res-3.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco/v1475601654/fnf9wrr2hwc2tbmpxpt5.png",
    rating: 4.4,
    position: "MM",
    features: [
      { value: "4.4", title: "FE" },
      { value: "5.1", title: "BE" },
      { value: "4.5", title: "DO" },
      { value: "6.8", title: "MM" },
      { value: "5.6", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Jonathan Buitrago",
    nick: "Jonny",
    avatar: "https://ca.slack-edge.com/T0351LEFK-U4NT4BMV2-fe287bf98912-512",
    project: "https://www.bvc.com.co/nueva/img/logo-bvc.png",
    rating: 4.2,
    position: "MM",
    features: [
      { value: "4.2", title: "FE" },
      { value: "2.1", title: "BE" },
      { value: "1.2", title: "DO" },
      { value: "6", title: "MM" },
      { value: "6", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Alejandro Gonzalez",
    nick: "Wisi",
    avatar: "https://ca.slack-edge.com/T0351LEFK-UN7DEDDC7-5a220e46ca6e-512",
    project: "https://www.bvc.com.co/nueva/img/logo-bvc.png",
    rating: 6.1,
    position: "BE",
    features: [
      { value: "5.5", title: "FE" },
      { value: "6.5", title: "BE" },
      { value: "3.7", title: "DO" },
      { value: "7.8", title: "MM" },
      { value: "6.2", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Ivan Gonzalez",
    nick: "Ivancho",
    avatar: "https://ca.slack-edge.com/T0351LEFK-UQ41K2S9M-0a2e09d31d48-512",
    project:
      "https://res-3.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco/v1475601654/fnf9wrr2hwc2tbmpxpt5.png",
    rating: 5.2,
    position: "BE",
    features: [
      { value: "3.6", title: "FE" },
      { value: "6.0", title: "BE" },
      { value: "4.7", title: "DO" },
      { value: "6.6", title: "MM" },
      { value: "5.9", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Juan Camargo",
    nick: "Juan",
    avatar: "https://ca.slack-edge.com/T0351LEFK-UPUJPL5A7-9b4331351c99-512",
    project:
      "https://res-3.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco/v1475601654/fnf9wrr2hwc2tbmpxpt5.png",
    rating: 4.7,
    position: "BE",
    features: [
      { value: "3.6", title: "FE" },
      { value: "6.3", title: "BE" },
      { value: "3.7", title: "DO" },
      { value: "5.0", title: "MM" },
      { value: "5.2", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Javier Vasquez",
    nick: "Javis",
    avatar: "https://ca.slack-edge.com/T0351LEFK-UKR7T23A6-c85a3804417a-512",
    project: "https://www.bancoldex.com/sites/default/files/1100ascenso.jpg",
    rating: 5.6,
    position: "FE",
    features: [
      { value: "5.1", title: "FE" },
      { value: "4.8", title: "BE" },
      { value: "3.2", title: "DO" },
      { value: "6.3", title: "MM" },
      { value: "6.5", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
  {
    name: "Luis Cataño",
    nick: "Luchox",
    avatar: "https://ca.slack-edge.com/T0351LEFK-UMRL75WJV-45145ebbf405-512",
    project: "https://www.bancoldex.com/sites/default/files/1100ascenso.jpg",
    rating: 5.3,
    position: "FE",
    features: [
      { value: "5.9", title: "FE" },
      { value: "4.8", title: "BE" },
      { value: "2.5", title: "DO" },
      { value: "6.1", title: "MM" },
      { value: "5.9", title: "GC" },
      { value: "7", title: "A" },
    ],
  },
];
